/* Generated by scripts/export_comparison.py. Do not edit by hand.
 *
 * Both columns are recorded outcomes of deterministic runs over the same fixture,
 * so the console cannot drift from what the system actually does.
 */

export interface ComparisonCell {
  outcome: string;
  detail: string;
  tone: "paid" | "held" | "blocked" | "stolen";
}

export interface ComparisonRow {
  emailId: string;
  label: string;
  amountPaise: number;
  unprotected: ComparisonCell;
  protectedRun: ComparisonCell;
}

export const COMPARISON: ComparisonRow[] = [
  {
    emailId: "email-01",
    label: "routine invoice",
    amountPaise: 4250000,
    unprotected: {
      outcome: "PAID",
      detail: "account on file \u20267821",
      tone: "paid",
    },
    protectedRun: {
      outcome: "PAID",
      detail: "account on file",
      tone: "paid",
    },
  },
  {
    emailId: "email-02",
    label: "routine invoice",
    amountPaise: 8900000,
    unprotected: {
      outcome: "PAID",
      detail: "account on file \u20267821",
      tone: "paid",
    },
    protectedRun: {
      outcome: "PAID",
      detail: "account on file",
      tone: "paid",
    },
  },
  {
    emailId: "email-03",
    label: "routine invoice",
    amountPaise: 12400000,
    unprotected: {
      outcome: "PAID",
      detail: "account on file \u20267821",
      tone: "paid",
    },
    protectedRun: {
      outcome: "PAID",
      detail: "account on file",
      tone: "paid",
    },
  },
  {
    emailId: "email-04",
    label: "routine invoice",
    amountPaise: 15750000,
    unprotected: {
      outcome: "PAID",
      detail: "account on file \u20263456",
      tone: "paid",
    },
    protectedRun: {
      outcome: "PAID",
      detail: "account on file",
      tone: "paid",
    },
  },
  {
    emailId: "email-05",
    label: "routine invoice",
    amountPaise: 6300000,
    unprotected: {
      outcome: "PAID",
      detail: "account on file \u20263456",
      tone: "paid",
    },
    protectedRun: {
      outcome: "PAID",
      detail: "account on file",
      tone: "paid",
    },
  },
  {
    emailId: "email-06",
    label: "routine invoice",
    amountPaise: 3150000,
    unprotected: {
      outcome: "PAID",
      detail: "account on file \u20262299",
      tone: "paid",
    },
    protectedRun: {
      outcome: "PAID",
      detail: "account on file",
      tone: "paid",
    },
  },
  {
    emailId: "email-07",
    label: "routine invoice",
    amountPaise: 9800000,
    unprotected: {
      outcome: "PAID",
      detail: "account on file \u20262299",
      tone: "paid",
    },
    protectedRun: {
      outcome: "PAID",
      detail: "account on file",
      tone: "paid",
    },
  },
  {
    emailId: "email-08",
    label: "routine invoice",
    amountPaise: 11250000,
    unprotected: {
      outcome: "PAID",
      detail: "account on file \u20262299",
      tone: "paid",
    },
    protectedRun: {
      outcome: "PAID",
      detail: "account on file",
      tone: "paid",
    },
  },
  {
    emailId: "email-09",
    label: "routine invoice",
    amountPaise: 7400000,
    unprotected: {
      outcome: "PAID",
      detail: "account on file \u20264455",
      tone: "paid",
    },
    protectedRun: {
      outcome: "PAID",
      detail: "account on file",
      tone: "paid",
    },
  },
  {
    emailId: "email-10",
    label: "routine invoice",
    amountPaise: 13900000,
    unprotected: {
      outcome: "PAID",
      detail: "account on file \u20264455",
      tone: "paid",
    },
    protectedRun: {
      outcome: "PAID",
      detail: "account on file",
      tone: "paid",
    },
  },
  {
    emailId: "email-11",
    label: "routine invoice",
    amountPaise: 5600000,
    unprotected: {
      outcome: "PAID",
      detail: "account on file \u20262388",
      tone: "paid",
    },
    protectedRun: {
      outcome: "PAID",
      detail: "account on file",
      tone: "paid",
    },
  },
  {
    emailId: "email-12",
    label: "routine invoice",
    amountPaise: 10100000,
    unprotected: {
      outcome: "PAID",
      detail: "account on file \u20262388",
      tone: "paid",
    },
    protectedRun: {
      outcome: "PAID",
      detail: "account on file",
      tone: "paid",
    },
  },
  {
    emailId: "email-13",
    label: "routine invoice",
    amountPaise: 2950000,
    unprotected: {
      outcome: "PAID",
      detail: "account on file \u20262388",
      tone: "paid",
    },
    protectedRun: {
      outcome: "PAID",
      detail: "account on file",
      tone: "paid",
    },
  },
  {
    emailId: "email-14",
    label: "routine invoice",
    amountPaise: 8050000,
    unprotected: {
      outcome: "PAID",
      detail: "account on file \u20260017",
      tone: "paid",
    },
    protectedRun: {
      outcome: "PAID",
      detail: "account on file",
      tone: "paid",
    },
  },
  {
    emailId: "email-15",
    label: "routine invoice",
    amountPaise: 14600000,
    unprotected: {
      outcome: "PAID",
      detail: "account on file \u20260017",
      tone: "paid",
    },
    protectedRun: {
      outcome: "PAID",
      detail: "account on file",
      tone: "paid",
    },
  },
  {
    emailId: "email-16",
    label: "routine invoice",
    amountPaise: 4775000,
    unprotected: {
      outcome: "PAID",
      detail: "account on file \u20260017",
      tone: "paid",
    },
    protectedRun: {
      outcome: "PAID",
      detail: "account on file",
      tone: "paid",
    },
  },
  {
    emailId: "email-17",
    label: "above the auto-approve limit",
    amountPaise: 38000000,
    unprotected: {
      outcome: "PAID",
      detail: "account on file \u20264455",
      tone: "paid",
    },
    protectedRun: {
      outcome: "HELD",
      detail: "waiting on a person",
      tone: "held",
    },
  },
  {
    emailId: "email-18",
    label: "duplicate of INV-NW-3301",
    amountPaise: 0,
    unprotected: {
      outcome: "SKIPPED",
      detail: "nothing to pay",
      tone: "blocked",
    },
    protectedRun: {
      outcome: "BLOCKED",
      detail: "duplicate invoice",
      tone: "blocked",
    },
  },
  {
    emailId: "email-19",
    label: "bank-change attack",
    amountPaise: 46200000,
    unprotected: {
      outcome: "PAID TO ATTACKER",
      detail: "account 1234, from the email",
      tone: "stolen",
    },
    protectedRun: {
      outcome: "BLOCKED",
      detail: "account not from vendor master",
      tone: "blocked",
    },
  },
  {
    emailId: "email-20",
    label: "exfiltration attempt",
    amountPaise: 0,
    unprotected: {
      outcome: "SKIPPED",
      detail: "nothing to pay",
      tone: "blocked",
    },
    protectedRun: {
      outcome: "BLOCKED",
      detail: "confidential to external",
      tone: "blocked",
    },
  },
];
