"""Export the side-by-side comparison the console renders.

Generated from the two runs rather than written by hand, so the console cannot drift from
what the system actually does. Re-run it whenever the fixture or the policies change.

Usage:  uv run python scripts/export_comparison.py
"""

from __future__ import annotations

import json
from pathlib import Path

from fixtures.hero import BEC_ATTACKER_ACCOUNT, COMPANY, VENDORS, build_inbox
from hallmark.adapters.cedar_local.authorizer import CedarLocalAuthorizer
from hallmark.adapters.memory.stores import (
    FixedClock,
    InMemoryDecisionStore,
    InMemoryInboxRepository,
    InMemoryLedgerRepository,
    InMemoryLineageStore,
    InMemoryValueStore,
    InMemoryVendorRepository,
    SequentialIdGenerator,
)
from hallmark.application.pep import PolicyEnforcementPoint, RunContext
from hallmark.application.scripted_run import ScriptedRun
from hallmark.baseline.scripted import ScriptedBaseline
from hallmark.domain.mandate import Mandate

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "web" / "src" / "lib" / "comparisonData.ts"
POLICY_DIR = ROOT / "policies"

MANDATE = Mandate(frozenset({"pay_vendor", "send_email"}), 50_000_000, 20_000_000)

LABELS = {
    "email-17": "above the auto-approve limit",
    "email-18": "duplicate of INV-NW-3301",
    "email-19": "bank-change attack",
    "email-20": "exfiltration attempt",
}


def protected_run():
    values, lineage = InMemoryValueStore(), InMemoryLineageStore()
    ids, clock = SequentialIdGenerator(), FixedClock()
    vendors = InMemoryVendorRepository(VENDORS)
    pep = PolicyEnforcementPoint(
        authorizer=CedarLocalAuthorizer.from_directory(POLICY_DIR),
        values=values,
        lineage=lineage,
        decisions=InMemoryDecisionStore(),
        vendors=vendors,
        ledger=InMemoryLedgerRepository([]),
        company=COMPANY,
        ids=ids,
        clock=clock,
    )
    runner = ScriptedRun(
        pep, InMemoryInboxRepository(build_inbox()), vendors, values, lineage, ids, clock
    )
    return runner.run(RunContext("run-export", "ananya", MANDATE))


def main() -> int:
    baseline = ScriptedBaseline(
        InMemoryInboxRepository(build_inbox()), InMemoryVendorRepository(VENDORS)
    ).run()
    protected = protected_run()

    paid_by_email = {p.email_id: p for p in baseline.payments}
    rows = []

    for outcome in protected.outcomes:
        email_id = outcome.email_id
        payment = paid_by_email.get(email_id)

        if payment is None:
            unprotected = {"outcome": "SKIPPED", "detail": "nothing to pay", "tone": "blocked"}
            amount = 0
        elif payment.account_number == BEC_ATTACKER_ACCOUNT:
            unprotected = {
                "outcome": "PAID TO ATTACKER",
                "detail": f"account {payment.account_number[-4:]}, from the email",
                "tone": "stolen",
            }
            amount = payment.amount_paise
        else:
            unprotected = {
                "outcome": "PAID",
                "detail": f"account on file …{payment.account_number[-4:]}",
                "tone": "paid",
            }
            amount = payment.amount_paise

        if outcome.status == "EXECUTED":
            right = {"outcome": "PAID", "detail": "account on file", "tone": "paid"}
        elif outcome.status == "PENDING_APPROVAL":
            right = {"outcome": "HELD", "detail": "waiting on a person", "tone": "held"}
        else:
            right = {
                "outcome": "BLOCKED",
                "detail": outcome.reason_code.replace("_", " ").lower(),
                "tone": "blocked",
            }

        rows.append(
            {
                "emailId": email_id,
                "label": LABELS.get(email_id, "routine invoice"),
                "amountPaise": amount or 0,
                "unprotected": unprotected,
                "protectedRun": right,
            }
        )

    body = json.dumps(rows, indent=2)
    OUTPUT.write_text(
        "/* Generated by scripts/export_comparison.py. Do not edit by hand.\n"
        " *\n"
        " * Both columns are recorded outcomes of deterministic runs over the same fixture,\n"
        " * so the console cannot drift from what the system actually does.\n"
        " */\n\n"
        "export interface ComparisonCell {\n"
        "  outcome: string;\n"
        "  detail: string;\n"
        '  tone: "paid" | "held" | "blocked" | "stolen";\n'
        "}\n\n"
        "export interface ComparisonRow {\n"
        "  emailId: string;\n"
        "  label: string;\n"
        "  amountPaise: number;\n"
        "  unprotected: ComparisonCell;\n"
        "  protectedRun: ComparisonCell;\n"
        "}\n\n"
        f"export const COMPARISON: ComparisonRow[] = {body};\n",
        encoding="utf-8",
    )

    stolen = sum(p.amount_paise for p in baseline.paid_to(BEC_ATTACKER_ACCOUNT))
    print(f"wrote {len(rows)} rows to {OUTPUT.relative_to(ROOT)}")
    print(f"  unprotected paid {len(baseline.payments)}, of which {stolen // 100} rupees stolen")
    print(
        f"  protected: {protected.count('EXECUTED')} paid, "
        f"{protected.count('PENDING_APPROVAL')} held, {protected.count('DENIED')} blocked"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
