"""Point the console at the stack that exists.

The API id changes every time the stack is recreated, and the console reads it from
`web/.env.local`. That file used to carry a comment saying the deploy wrote it, while
nothing did: after a recreate the console kept calling the previous deployment's id and
every request failed with a 404 that looked like a broken API rather than a stale address.

Run from the deploy, so the file cannot drift from the stack again.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from hallmark.config import Settings, local_boto3_client  # noqa: E402

STACK_NAME = "hallmark"
TARGET = Path(__file__).resolve().parents[1] / "web" / ".env.local"
GATEWAY = "ws://127.0.0.1:8787/events"


def main() -> int:
    client = local_boto3_client("cloudformation", Settings.from_env())

    try:
        outputs = client.describe_stacks(StackName=STACK_NAME)["Stacks"][0].get("Outputs", [])
    except Exception:
        print(f"# stack '{STACK_NAME}' is not deployed; skipping console env", file=sys.stderr)
        return 0

    api_url = next((o["OutputValue"] for o in outputs if o["OutputKey"] == "ApiUrl"), None)
    if not api_url:
        print("# stack has no ApiUrl output; skipping console env", file=sys.stderr)
        return 0

    TARGET.write_text(
        "# Generated by `make deploy-local`. The API id changes on every stack recreate,\n"
        "# so edit the deploy rather than this file.\n"
        f"VITE_API_TARGET={api_url}\n"
        f"VITE_GATEWAY_WS={GATEWAY}\n",
        encoding="utf-8",
    )
    print(f"console env -> {api_url}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
